### ISSUE TITLE
LBT 1.6

### ISSUE THREAD

**Issue by Shaq1401** [ladybug-tools/lbt-grasshopper-samples#1]
Hello !
I cannot open any of the Ladybug 1.6 sample files. Get this error :

Grasshopper Event Log 

 This document contains the messages that were recorded during the most recent Grasshopper® file read/write. Whenever a read/write operation fails or behaves unexpectedly, this summary will be compiled and put on display. If you experience problems saving or opening files, please include this log with any bug-report you file. You can use the Send... button to mail this report directly, or you can save the log and attach it to a personal email message. This log contains no personal information beyond what you supply, nor any other information that is not directly related to Grasshopper. 

[ Developer contact ](https://discourse.mcneel.com/) 

 Message log start (chronological): 

 IO Read error: Unknown data type encountered.

**Comment by mostaphaRoudsari** [comment]
Hi @Shaq1401, How did you install the plugin?

**Comment by Shaq1401** [comment]
Hello Mostapha!
I download 1.6.0 via Food4rhino, unblocked the Zip, unzipped, and installed according to the instructions text. ran the installer.gh, and also did the optional steps to install Radiance, OpenStudio, etc. 
regards
Shahrokh

**Comment by mostaphaRoudsari** [comment]
Can you try to install the plugin using the Pollination Grasshopper single-click installer? It installs the latest version of Ladybug Tools and the engines.

I feel the source of the error is that you are using an older version of Rhino. Try to update your Rhino installation to the latest version.

**Comment by Shaq1401** [comment]
You mean from this link:
![image](https://user-images.githubusercontent.com/125478946/219314413-c8cc1a14-248e-45d6-b0ee-c65f1fc6b72a.png)

**Comment by mostaphaRoudsari** [comment]
Yes

**Comment by Shaq1401** [comment]
Ok ! I did that , also installed latest Rhino. same error. The thing is that I can start working with all LBT nodes in an empty canvas. So the plugin is running fine, there is something in those examples that I can't open.

**Comment by mostaphaRoudsari** [comment]
It is most likely that the sample files are created by Rhino 7 and you are using Rhino 6 or something like that. In any case, at this point this is not really a Ladybug Tools issue. You may want to post it to McNeel's forum: https://discourse.mcneel.com
